---
default: true

# MD003/heading-style/header-style - Heading style
MD003:
  style: atx

# MD004/ul-style - Unordered list style
MD004:
  style: asterisk

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 4

# MD013/line-length - Line length
MD013:
  line_length: 120

# MD025/single-title/single-h1 - Multiple top-level headings
# in the same document
MD025: false

# MD030/list-marker-space - Spaces after list markers
MD030:
  ul_multi: 1
  ol_multi: 2

# MD035/hr-style - Horizontal rule style
MD035:
  style: ---

# MD035/hr-style - First line should be top-level heading style
MD041: False

# MD046/code-block-style - Code block style
MD046: false
