site_name: Yggdrasil

nav:
  - Introduction: index.md
  - Health:
      - Sleep: health/sleep.md
      - Fitness: health/fitness.md
  - DevOps:
      - devops/index.md
      - Bash: devops/bash.md
      - Setup mkdocs:
          - Getting started: devops/setup-docs/getting-started.md
          - Tools & plugins: devops/setup-docs/tools-plugins.md
  - Coding:
      - Architecture:
          - Repository pattern: coding/architecture/repository-pattern.md
          - Domain Driven Design: coding/architecture/ddd.md
      - Intellij IDEA: coding/intellij-idea.md
      - Python:
          - coding/python/index.md
          - Libraries:
              - SQLAlchemy: coding/python/libraries/sqlalchemy.md
          - Data structures: coding/python/data-structures.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - encryptcontent:
      title_prefix: '[lock] '
      button_class: 'md-search__icon'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: true
      baselevel: 2
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
