site_name: Codex Astrum

nav:
  - Introduction: index.md
  - Health:
      - Sleep: health/sleep.md
      - Fitness: health/fitness.md
  - Projects:
      - Gitlab analyzer:
          - projects/glab-analyzer/index.md
  - Coding:
      - Coding basics:
          - coding/basics/index.md
          - Setup coding environment: coding/basics/setup-coding-env.md
      - Languages:
          - Python:
              - coding/python/index.md
              - Python setup: coding/python/python-setup.md
              - Project templates:
                  - Web apps: coding/python/project_templates/web_apps.md
              - Data structures: coding/python/data-structures.md
              - Libraries:
                  - Alembic: coding/python/libraries/alembic.md
                  - FastAPI: coding/python/libraries/fastapi.md
                  - Pydantic: coding/python/libraries/pydantic.md
                  - SQLAlchemy: coding/python/libraries/sqlalchemy.md
                  - Uvicorn: coding/python/libraries/uvicorn.md
          - SQL:
              coding/sql/index.md
      - Software Architecture:
        - Repository pattern: coding/architecture/repository-pattern.md
        - Domain Driven Design: coding/architecture/ddd.md
        - Entity relationship modelling: coding/architecture/entity-relationship.md
  - MacOs:
      - macos/index.md
      - Libraries:
          - Tree: macos/libraries/tree.md
  - Tooling:
      MkDocs: tooling/setup-mkdocs.md
      Bash: tooling/bash.md
      Intellij IDEA: tooling/intellij-idea.md
  - DevOps:
      - devops/index.md
      - devops/docker.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - encryptcontent:
      title_prefix: '[lock] '
      button_class: 'md-search__icon'
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - md_in_html
  - def_list
  - toc:
      permalink: true
      baselevel: 2
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
